### ISSUE TITLE
Can't exit PseudoTV (Apple TV 2)

### ISSUE THREAD

**Issue by namliz** [Jasonra/XBMC-PseudoTV#12]
The Apple remote only has 3 additional buttons besides the navigation pad. 
In short, as a result there is no way to exit PseudoTV once it gets going other than doing a hard reset! :P

**Comment by Jasonra** [comment]
Yea, not being able to exit really is a problem.  I guess I do have to come up with some solution for this to allow the Previous Menu button.  Perhaps a timed (3 sec or so) confirmation on the first press to make sure it  wasn't an accident.  I will experiment.

**Comment by Jasonra** [comment]
Fixed in latest stable-pre.  The Previous Menu key will now invoke a prompt to confirm the user wants to exit.  This should satisfy the need to prevent accidental exits, but also to function with limited key availability (ie. Apple remote).
