### ISSUE TITLE
EPG Colors hex values truncated

### ISSUE THREAD

**Issue by josebiro** [Jasonra/XBMC-PseudoTV#20]
when converting the int values to hex using the index offset -1, color values are truncated. [2:-1] should just be [2:]

**Comment by josebiro** [comment]
This is visible in several skins, but I noticed it on mettropolis(svn). I've created patch a0a59a0f59934f5e17edcf2430865b965528a6d3 created to address, but have never used github and submitting pull requests confuses me.

**Comment by Jasonra** [comment]
Github is apparently having problems and says it can't find the patch.  Can you put it in a comment here?

**Comment by josebiro** [comment]
commit a0a59a0f59934f5e17edcf2430865b965528a6d3
Author: Joseph Bironas josebiro@gmail.com
Date:   Mon Feb 20 12:29:39 2012 -0800

```
Removing -1 index that truncates color values in the EPG
```

```
diff --git a/resources/lib/EPGWindow.py b/resources/lib/EPGWindow.py
index eb2c44c..5022752 100644
--- a/resources/lib/EPGWindow.py
+++ b/resources/lib/EPGWindow.py
@@ -113,10 +113,10 @@ class EPGWindow(xbmcgui.WindowXMLDialog):
             focusedcolor = int(self.getControl(100).getLabel2(), 16)

             if textcolor > 0:
-                self.textcolor = hex(textcolor)[2:-1]
+                self.textcolor = hex(textcolor)[2:]

             if focusedcolor > 0:
-                self.focusedcolor = hex(focusedcolor)[2:-1]
+                self.focusedcolor = hex(focusedcolor)[2:]
         except:
             pass

```

**Comment by Jasonra** [comment]
Committed, thank you.
