### ISSUE TITLE
epg and info sync issue

### ISSUE THREAD

**Issue by ez1976** [Jasonra/XBMC-PseudoTV#34]
hi 
i found a weird bug and i hope someone can direct me in the right direction.

when PTV populate the channels, it takes the info of the movies to display in the info bar.
when the description on the movie exceed 500 characters (more or less. the line including the movie name is more than 520 characters), PTV cannot display it and show the next movie's info.
once i edit the channel file (the m3u ) and reduce the file to 550 characters, the info displays it ok.

i think PTV cannot handle long movie information.
now my question is, does anyone know where the in the PTV scripts, there is the parameter? and maybe add a line that tells it only to import not all the info of the movie (it doesnt fit in the info screen anyway)
this goes the same for the EPG windows.
maybe that is the source of the EPG sync issues?

thanks

EDIT: when editing the m3u files, i found out that lines that are not showing in the EPG are lines that have a total of 609 characters (including movie name). it is always 609 so maybe there is a parameter somewhere in PTV' s system files that:
- either import 609 characters and cannot display them
- epg and tv overlay info cannot display info that has 609 characters

this takes the epg out of sync.

so there is a need to change the import settings or display settings.
anyone have an idea what needs to be done?
thanks

**Comment by Jasonra** [comment]
This is not exactly a PTV issue (as far as I can tell).  I added a limit long ago to fix a problem with XBMC reading a line from a playlist that was too long.  I honestly don't know what the issue is, if it's a buffer-length problem, or some problematic character.  In any case, I know that I limited it to 600 at one point, and you limited it to 520 to fix your issues.  I went ahead and shrunk it to 500 characters...hopefully that will solve the vast majority of problems.

**Comment by ez1976** [comment]
Thanks.
Where can I download the new file ?

**Comment by ez1976** [comment]
as soon as i reduced the lines on the DB itself to 520, the EPG and info issues were resolved.
your solution is better of course.
how can i download and install your fix?
thanks

**Comment by Jasonra** [comment]
Just download stable-pre, it is there (asking with a few other small fixes)

**Comment by ez1976** [comment]
dude. what can i say? thanks a bunch
do you have a paypal account for a donation?
after all you did reinvent my whole media center / tv at home. :)

**Comment by Jasonra** [comment]
Link from http://forum.xbmc.org/showthread.php?tid=90738 - https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=ESJJ6RD43NB98&lc=US&item_name=PseudoTV%20Development&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_SM%2egif%3aNonHosted
